# DNSé˜²æ³„éœ²ç‰ˆæœ¬
# å¿…è¯»ï¼ï¼ï¼
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…

# é”šç‚¹
Fallback: &Fallback {type: select, proxies: [ğŸ” ç‹®åŸæ•…è½¬, ğŸ” å°æ¹¾æ•…è½¬, ğŸ” æ—¥æœ¬æ•…è½¬, ğŸ” é¦™æ¸¯æ•…è½¬, ğŸ” ç¾å›½æ•…è½¬, ğŸ” èŠ‚ç‚¹æ•…è½¬, ğŸŒ æ”¾è¡ŒèŠ‚ç‚¹, ğŸ”— ç›´è¿, ğŸš« æ‹’ç»]}

proxy-providers:
  WD:
    url: "æœºåœºè®¢é˜…URL"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸ”— ç›´è¿

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ğŸ”— ç›´è¿, type: direct}
  - {name: ğŸš« æ‹’ç», type: reject}

# å…¨å±€é…ç½® 
mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# ä¸ºé˜²æ­¢ä½¿ç”¨æ’ä»¶æœ‹å‹é‡åˆ°é¢æ¿é—®é¢˜ï¼Œæˆ‘æ³¨é‡Šæ‰äº†æ­¤æ¨¡å—ã€‚
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: ui
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢ï¼ˆfakeipä¸‹å…¶å®å¯ä»¥ä¸ç”¨å—…æ¢ï¼‰
#sniffer:
#  enable: true
#  sniff:
#    HTTP:
#      ports: [80, 8080-8880]
#      override-destination: true
#    TLS:
#      ports: [443, 8443]
#    QUIC:
#      ports: [443, 8443]
#  skip-domain:
#    - "Mijia Cloud"
#    - "+.push.apple.com"

# å…¥ç«™
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #ä½¿ç”¨nikkiï¼Œæ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
  #device: nikki
  #ä½¿ç”¨ä»…å†…æ ¸è‡ªè¡Œä¿®æ”¹ä¸‹é¢ä¸‰é¡¹ä¸ºtrue
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNSæ¨¡å—
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  resolve-concurrent: true                                      # DNSå¹¶å‘è§£æå¼€å…³
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://8.8.8.8/dns-query
  fake-ip-filter:
    - 'rule-set:blacklist_domain'                               # è‡ªå»ºåŸŸåé»‘åå•è§„åˆ™é›†
    - 'rule-set:blacklist_classical'                            # è‡ªå»ºåŸŸåé»‘åå•è§„åˆ™é›†    
    - 'rule-set:realip_domain_direct'                           # è‡ªå»ºä¸ä½¿ç”¨fakeipçš„ä»£ç†çš„è§„åˆ™é›†
    - 'rule-set:realip_domain_proxy'                            # è‡ªå»ºä¸ä½¿ç”¨fakeipçš„ç›´è¿çš„è§„åˆ™é›†
  nameserver-policy:
    'rule-set:blacklist_domain':                                # è‡ªå»ºåŸŸåé»‘åå•è§„åˆ™é›†,DNSä¸è§£æ
      - 0.0.0.0
    'rule-set:blacklist_classical':                             # è‡ªå»ºåŸŸåé»‘åå•è§„åˆ™é›†,DNSä¸è§£æ
      - 0.0.0.0
    'rule-set:realip_domain_direct':
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    'rule-set:realip_domain_proxy':
      - https://8.8.8.8/dns-query
      - tls://1.1.1.1:853
      - https://1.0.0.1/dns-query

# å‡ºç«™ç­–ç•¥ï¼Œæ ¹æ®è‡ªå·±æƒ…å†µè°ƒæ•´æ¯ä¸ªç­–ç•¥é‡Œåˆ†ç»„æ’åºï¼Œå¢åˆ éƒ½å¯ä»¥ï¼Œæ¯”å¦‚æŠŠç¾å›½è‡ªåŠ¨æ”¾åˆ°ç¬¬ä¸€ä¸ªï¼Œæ¯”å¦‚åˆ é™¤é¦™æ¸¯æ•…è½¬ï¼Œæ³¨æ„åˆ«æ¼æ‰è¡¨æƒ…é€—å·ç­‰ã€‚
# å¦‚æœç›¸åº”åˆ†ç»„æ²¡æœ‰ç­›é€‰åˆ°å¯¹åº”çš„å›½å®¶ï¼Œè¯·æ ¹æ®è‡ªå·±èŠ‚ç‚¹åå­—è°ƒæ•´ç­›é€‰å…³é”®å­—ã€‚
# æ²¡æœ‰å†ä½¿ç”¨é”šç‚¹ï¼Œæ˜¯è€ƒè™‘å¾ˆå¤šæ–°æ‰‹ä¿®æ”¹éš¾åº¦ï¼Œè¿™æ ·æ–°æ‰‹ä¿®æ”¹æŸä¸ªåˆ†ç»„æ›´å®¹æ˜“äº›ã€‚
proxy-groups:
  # ç­–ç•¥
  - {name: ğŸ” Google, <<: *Fallback}
  - {name: ğŸ“² Telegram, <<: *Fallback}
  - {name: ğŸ¤– AI, <<: *Fallback}
  - {name: ğŸ’» Github, <<: *Fallback}
  - {name: ğŸ“¹ YouTube, <<: *Fallback}
  - {name: ğŸ® æ¸¸æˆ, <<: *Fallback}
  - {name: ğŸªŸ Microsoft, <<: *Fallback}
  - {name: ğŸ¥ TikTok, <<: *Fallback}
  - {name: ğŸ“º Netflix, <<: *Fallback}
  - {name: ğŸ° Disney, <<: *Fallback}
  - {name: ğŸï¸ HBO Max, <<: *Fallback}
  - {name: ğŸ“½ï¸ Apple TV, <<: *Fallback}
  - {name: ğŸ§ Spotify, <<: *Fallback}
  - {name: ğŸ¦ Twitter / X, <<: *Fallback}
  - {name: ğŸ‘½ Reddit, <<: *Fallback}
  - {name: ğŸ’¬ WhatsApp, <<: *Fallback}
  - {name: ğŸ’¶ PayPal, <<: *Fallback}
  - {name: ğŸ›¡ï¸ æµé‡å‡€åŒ–, <<: *Fallback}
  - {name: ğŸ“¡ æ¶ˆæ¯æ¨é€, <<: *Fallback}
  - {name: ğŸ”— ç›´è¿æœåŠ¡, <<: *Fallback}
  - {name: ğŸš€ å¤–ç½‘å…œåº•, <<: *Fallback}
  - {name: ğŸ§¯ å…¨å±€å…œåº•, <<: *Fallback}
  # èŠ‚ç‚¹
  - {name: ğŸŒ æ”¾è¡ŒèŠ‚ç‚¹, type: select, include-all: true, filter: "^((?!(ç›´è¿|æ‹’ç»|DIRECT|reject)).)*$"}
  # æ•…è½¬
  - {name: ğŸ” ç‹®åŸæ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(å°|æ—¥|éŸ©|æ·±|ç¾)).)*$"}
  - {name: ğŸ” å°æ¹¾æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(å°|å°æ¹¾|ğŸ‡¹ğŸ‡¼|(?i)Taiwan))^((?!(æ¸¯|ç¾|éŸ©|æ–°|æ—¥|US|States|America)).)*$"}
  - {name: ğŸ” æ—¥æœ¬æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$"}
  - {name: ğŸ” é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ” ç¾å›½æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|éŸ©|æ–°|æ—¥)).)*$"}
  - {name: ğŸ” èŠ‚ç‚¹æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "^((?!(ç›´è¿|æ‹’ç»|DIRECT|reject)).)*$"}


# è§„åˆ™åŒ¹é…
rules:
  # ğŸ›¡ï¸ æµé‡å‡€åŒ– (æŒ‰å±é™©ä¼˜å…ˆçº§æ’åº)
  - RULE-SET,google_ads_domain,ğŸ›¡ï¸ æµé‡å‡€åŒ–          # è°·æ­Œå¹¿å‘Š
  - RULE-SET,disney_ads_domain,ğŸ›¡ï¸ æµé‡å‡€åŒ–          # disneyå¹¿å‘Š
  - RULE-SET,apple_ads_domain,ğŸ›¡ï¸ æµé‡å‡€åŒ–           # appleå¹¿å‘Š
  - RULE-SET,ad_domain,ğŸ›¡ï¸ æµé‡å‡€åŒ–                  # å¹¿å‘Š
  # è‡ªå»ºè§„åˆ™é›†ï¼ˆæµé‡å¤„ç†æ–¹å¼å€Ÿç”¨å·²é…ç½®ç­–ç•¥ç»„ï¼‰
    # é»‘åå•
  - RULE-SET,blacklist_domain,ğŸ›¡ï¸ æµé‡å‡€åŒ–                  # è‡ªå»ºåŸŸåé»‘åå•è§„åˆ™é›†
  - RULE-SET,blacklist_classical,ğŸ›¡ï¸ æµé‡å‡€åŒ–               # è‡ªå»ºåŸŸåé»‘åå•è§„åˆ™é›†
  - RULE-SET,blacklist_ip,ğŸ›¡ï¸ æµé‡å‡€åŒ–,no-resolve           # è‡ªå»ºipé»‘åå•è§„åˆ™é›†
    # ç™½åå•
  - RULE-SET,whitelist_domain_direct,ğŸ”— ç›´è¿æœåŠ¡           # è‡ªå»ºç›´è¿åŸŸåç™½åå•è§„åˆ™é›†
  - RULE-SET,whitelist_ip_direct,ğŸ”— ç›´è¿æœåŠ¡,no-resolve    # è‡ªå»ºç›´è¿ipç™½åå•è§„åˆ™é›†
  - RULE-SET,whitelist_domain_proxy,ğŸš€ å¤–ç½‘å…œåº•            # è‡ªå»ºä»£ç†åŸŸåç™½åå•è§„åˆ™é›†
  - RULE-SET,whitelist_ip_proxy,ğŸš€ å¤–ç½‘å…œåº•,no-resolve     # è‡ªå»ºä»£ç†ipç™½åå•è§„åˆ™é›†
  # ğŸ“¡ æ¶ˆæ¯æ¨é€
  - RULE-SET,google_fcm_domain,ğŸ“¡ æ¶ˆæ¯æ¨é€          # GoogleFCM
  # å†…ç½‘ç›´è¿
  - RULE-SET,private_ip,ğŸ”— ç›´è¿æœåŠ¡,no-resolve
  - RULE-SET,private_domain,ğŸ”— ç›´è¿æœåŠ¡
  # ğŸ’¶ PayPal
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  # ğŸ“² Telegram
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  # ğŸ“¹ YouTube
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  # ğŸ¤– AI
  - RULE-SET,ai_domain,ğŸ¤– AI
  # ğŸ’» Github
  - RULE-SET,github_domain,ğŸ’» Github
  # ğŸ¥ TikTok
  - RULE-SET,tiktok_domain,ğŸ¥ TikTok
  # ğŸ“º Netflix
  - RULE-SET,netflix_ip,ğŸ“º Netflix,no-resolve
  - RULE-SET,netflix_domain,ğŸ“º Netflix
  # ğŸ° Disney
  - RULE-SET,disney_domain,ğŸ° Disney
  # ğŸï¸ HBO Max
  - RULE-SET,hbo_domain,ğŸï¸ HBO Max
  # ğŸ“½ï¸ Apple TV
  - RULE-SET,apple_tvplus_domain,ğŸ“½ï¸ Apple TV
  # ğŸ§ Spotify
  - RULE-SET,spotify_domain,ğŸ§ Spotify
  # ğŸ® æ¸¸æˆ
  - RULE-SET,steam_unlock_domain,ğŸ® æ¸¸æˆ
  - RULE-SET,steam_domain,ğŸ® æ¸¸æˆ
  - RULE-SET,nintendo_domain,ğŸ® æ¸¸æˆ
  # ğŸ¦ Twitter / X
  - RULE-SET,twitter_domain,ğŸ¦ Twitter / X
  # ğŸ‘½ Reddit
  - RULE-SET,reddit_domain,ğŸ‘½ Reddit
  # ğŸ’¬ WhatsApp
  - RULE-SET,whatsapp_domain,ğŸ’¬ WhatsApp
  # ğŸªŸ Microsoft
  - RULE-SET,microsoft_cn_domain,ğŸªŸ Microsoft
  # ğŸ” Google
  - RULE-SET,google_scholar_domain,ğŸ” Google 
  - RULE-SET,google_gemini_domain,ğŸ” Google
  - RULE-SET,google_play_domain,ğŸ” Google
  - RULE-SET,google_ip,ğŸ” Google,no-resolve
  - RULE-SET,google_domain,ğŸ” Google
  # ğŸ”— ç›´è¿æœåŠ¡
    # æ¸¸æˆç›´è¿æœåŠ¡
  - RULE-SET,steam_cn_domain,ğŸ”— ç›´è¿æœåŠ¡ # steamç›´è¿
  - RULE-SET,nintendo_cn_domain,ğŸ”— ç›´è¿æœåŠ¡ # ä»»å¤©å ‚ç›´è¿
    # è‹¹æœç›´è¿æœåŠ¡
  - RULE-SET,apple_update_domain,ğŸ”— ç›´è¿æœåŠ¡
  - RULE-SET,apple_pki_domain,ğŸ”— ç›´è¿æœåŠ¡
  - RULE-SET,apple_cn_domain,ğŸ”— ç›´è¿æœåŠ¡
  # ğŸš€ å¤–ç½‘å…œåº•
  - RULE-SET,geolocation-!cn,ğŸš€ å¤–ç½‘å…œåº•
    # å›½å†…ç›´è¿
  - RULE-SET,cn_domain,ğŸ”— ç›´è¿æœåŠ¡
  - RULE-SET,cn_ip,ğŸ”— ç›´è¿æœåŠ¡
  # ğŸ§¯ å…¨å±€å…œåº•
  - MATCH,ğŸ§¯ å…¨å±€å…œåº•


# è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  domain_text: &domain_text {type: http, interval: 86400, behavior: domain, format: text}
  ip_text: &ip_text {type: http, interval: 86400, behavior: ipcidr, format: text}
  classical_text: &classical_text {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  # è‡ªå»ºè§„åˆ™é›†
  realip_domain_direct: { <<: *domain_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/realip_domain_direct.txt" }           # è‡ªå®šä¹‰fakeipè¿‡æ»¤åŸŸåè§„åˆ™é›†,ç›´è¿DNS
  realip_domain_proxy: { <<: *domain_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/realip_domain_proxy.txt" }             # è‡ªå®šä¹‰fakeipè¿‡æ»¤åŸŸåè§„åˆ™é›†,ä»£ç†DNS
  whitelist_domain_direct: { <<: *domain_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/whitelist_domain_direct.txt" }     # è‡ªå®šä¹‰åŸŸåç™½åå•,ç›´è¿
  whitelist_domain_proxy: { <<: *domain_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/whitelist_domain_proxy.txt" }       # è‡ªå®šä¹‰åŸŸåç™½åå•,ä»£ç†
  whitelist_ip_direct: { <<: *ip_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/whitelist_ip_direct.txt" }                 # è‡ªå®šä¹‰ipç™½åå•,ç›´è¿
  whitelist_ip_proxy: { <<: *ip_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/whitelist_ip_proxy.txt" }                   # è‡ªå®šä¹‰ipç™½åå•,ä»£ç†
  blacklist_domain: { <<: *domain_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/blacklist_domain.txt" }                   # è‡ªå®šä¹‰é»‘åå•åŸŸå,ä¸è§£æDNS
  blacklist_ip: { <<: *ip_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/blacklist_ip.txt" }                               # è‡ªå®šä¹‰é»‘åå•ip
  blacklist_classical: { <<: *classical_text, url: "https://raw.githubusercontent.com/mqlszxy/configs/refs/heads/main/Nikki/blacklist_classical.txt" }          # è‡ªå®šä¹‰é»‘åå•
  # ğŸ›¡ï¸ æµé‡å‡€åŒ–
  ad_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs" }                           # MetaCubeXå®˜æ–¹å¹¿å‘Šè§„åˆ™
  # ğŸ”— ç›´è¿æœåŠ¡
  private_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs" }
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }
  # ğŸ” Google
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  google_fcm_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/googlefcm.mrs" }                  # GoogleFCM
  google_ads_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-ads.mrs" }                 # GoogleADS
  google_gemini_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-gemini.mrs" }           # GoogleGemini
  google_play_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-play.mrs" }               # GooglePlay
  google_scholar_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-scholar.mrs" }         # GoogleScholar
  # ğŸ“² Telegram
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  # ğŸ¤– AI
  ai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  # ğŸ’» Github
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  # ğŸ“¹ YouTube
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  # ğŸ¥ TikTok
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }
  # ğŸ“º Netflix
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  # ğŸ° Disney
  disney_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs" }
  disney_ads_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney@ads.mrs" }
  # ğŸï¸ HBO Max
  hbo_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.mrs" }
  # ğŸ§ Spotify
  spotify_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs" }
  # ğŸ¦ Twitter / X
  twitter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs" }
  # ğŸªŸ Microsoft
  microsoft_cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft@cn.mrs" }
  # ğŸ Apple
  apple_update_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-update.mrs" }
  apple_pki_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-pki.mrs" }
  apple_cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs" }
  apple_ads_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple@ads.mrs" }
  apple_tvplus_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-tvplus.mrs" }
  # ğŸ® æ¸¸æˆ
  steam_cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam@cn.mrs" }                     # steam
  steam_unlock_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steamunlocked.mrs" }
  steam_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs" }
  nintendo_cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/nintendo@cn.mrs" }               # nintendo
  nintendo_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/nintendo.mrs" }
  # ğŸ’¶ PayPal
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  # ğŸ‘½ Reddit
  reddit_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/reddit.mrs" }
  # ğŸ’¬ WhatsApp
  whatsapp_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/whatsapp.mrs" }
  # ğŸš€ å¤–ç½‘å…œåº•
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
